[package]
name = "wbp"
version = "0.1.0"
edition = "2024"

[dependencies]
ego-tree = "0.10.0"
scraper = "0.23.1"
softbuffer = "0.4.6"
tiny-skia = "0.11.4"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
url = "2.5.4"
winit = "0.30"

[profile.dev]
opt-level = 1
