[package]
name = "wbp"
version = "0.1.0"
edition = "2024"

[dependencies]
pixels = "0.15.0"
tiny-skia = "0.11.4"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
url = "2.5.4"
winit = "0.29"
winit_input_helper = "0.15"